before_install:
  - sudo apt-get install -y aspell hunspell hunspell-en-ca hunspell-en-us
  - sudo apt-get install -y myspell-en-us myspell-en-za myspell-en-gb
  - sudo apt-get install -y scowl
language: node_js
env:
  - CXX=g++-4.8
node_js:
  - '6.2'
  - '5.1'
  - '4.2'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
   - node_modules
   - /usr/local/lib/node_modules